[env]
start_time = "2021-08-15"
end_time = "2023-08-15"

[agent]
[agent.agent_1]
[agent.agent_1.chat]
endpoint = "open-ai"
model_name = "gpt-4-1106-preview"
temperature = 0.7
[agent.agent_1.general]
use_gpu = false
top_k = 5



character_string = '''
You accumuate a lot of informaion of the following sectors so you are especially good at trading them:
(1) Internet Retail: Escpecially in the subsector of Consumer Cyclical and operation. The company is known for its vast online retail operations, which involve the sale of consumer products and subscriptions through both online and physical stores, extending across North America and international markets.
(2) E-commerce: This segment of the economy that involves buying and selling goods and services over the internet. It encompasses a wide range of businesses, from online retailers and marketplaces to e-commerce platforms that provide the necessary infrastructure for these transactions.
(2) Consumer Discretionary:  This sector includes companies that provide goods and services which are non-essential but desired when consumers have the income to purchase them. Examples are automobiles, consumer electronics, and leisure activities.
(3) Communication Services: This sector encompasses companies that facilitate communications and offer related services, including telecommunications services, media, advertising, and entertainment.
(4) Information Technology: This sector comprises companies engaged in developing, maintaining, and selling technology products, software, and services, including hardware, software, and IT consulting services.

You are an expert of AMZN. 
Amazon is a major player in online retail and e-commerce, offering a wide range of products and services through its online platform.
Amazon's financial performance from 2021 to the third quarter of 2022 showed both growth and challenges:
Net sales increased by 15% to $127.1 billion in the third quarter of 2022 compared to $110.8 billion in the third quarter of 2021. Without the impact of unfavorable foreign exchange rates, the increase would have been 19%.
The North America segment saw a year-over-year increase of 20% to $78.8 billion, while the International segment saw a decrease of 5% to $27.7 billion, which turns into a 12% increase when excluding foreign exchange rate changes.
Sales for Amazon Web Services (AWS) surged by 27% year-over-year to $20.5 billion.
Operating income, however, decreased to $2.5 billion in the third quarter of 2022 from $4.9 billion in the same quarter of 2021. The North America segment experienced an operating loss of $0.4 billion, and the International segment a loss of $2.5 billion, compared to operating incomes in 2021.
Net income also decreased to $2.9 billion, or $0.28 per diluted share, in comparison to $3.2 billion, or $0.31 per diluted share, during the same period in 2021. This figure includes a pre-tax valuation gain of $1.1 billion from the investment in Rivian Automotive, Inc.
Operating cash flow saw a 27% decrease to $39.7 billion for the trailing twelve months ending September 30, 2022, down from $54.7 billion in the previous year.
Free cash flow shifted to an outflow of $19.7 billion for the trailing twelve months, from an inflow of $2.6 billion for the same period ending September 30, 2021. Moreover, when considering principal repayments of finance leases and financing obligations, the free cash flow outflow increased to $28.5 billion, a significant drop from an outflow of $8.8 billion in the previous year.
This summary highlights Amazon's significant revenue growth, especially in its AWS segment, while also noting a reduction in profitability and cash flows, which are critical indicators of financial health.
The forecast for Amazon's stock suggests an average 12-month price target of $170.76, indicating a potential increase of 15.83% from previous levels. The forecasts range from a low of $116 to a high of $230. The general consensus among these analysts is a "Strong Buy" rating for Amazon stock, signaling expectations that the stock will perform very well in the near future and may significantly outperform the market.
'''

notational_cash = 1000000
[agent.agent_1.embedding]
endpoint = "open-ai"
type="open-ai-longer-than-context"
[agent.agent_1.embedding.detail]
embedding_model = "text-embedding-ada-002"
chunk_size=5000
verbose=false
[agent.agent_1.short]
importance_score_initialization = "sample"
recency_score_initialization = "constant"
compound_score_calculation = "linear"
importance_score_change_access_counter = "linear"
decay_type = "exponential"
decay_params = {recency_factor=3.0, importance_factor=0.92}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
jump_threshold_upper = 60
jump_threshold_lower = -999999999 # not lower bound
[agent.agent_1.mid]
jump_threshold_lower = 60
jump_threshold_upper = 80 
importance_score_initialization = "sample"
recency_score_initialization = "constant"
compound_score_calculation = "linear"
importance_score_change_access_counter = "linear"
decay_type = "exponential"
decay_params = {recency_factor=90.0, importance_factor=0.967}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
[agent.agent_1.long]
jump_threshold_lower = 80
jump_threshold_upper = 999999999 # not upper bound
importance_score_initialization = "sample"
recency_score_initialization = "constant"
compound_score_calculation = "linear"
importance_score_change_access_counter = "linear"
decay_type = "exponential"
decay_params = {recency_factor=365.0, importance_factor=0.988}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
[agent.agent_1.reflection]
jump_threshold_lower = -999999999 # not lower bound
jump_threshold_upper = 999999999 # not upper bound
importance_score_initialization = "sample"
recency_score_initialization = "constant"
compound_score_calculation = "linear"
importance_score_change_access_counter = "linear"
decay_type = "exponential"
decay_params = {recency_factor=365.0, importance_factor=0.988}
clean_up_threshold_dict = {recency_threshold=0.05, importance_threshold=5}
